const LOGIN_PREFIX = 'Login';
const REGISTER_PREFIX = 'Register';

const ADMIN_CREATE_PREFIX = 'Create';
const ADMIN_DELETE_PREFIX = 'Delete';
const ADMIN_USERS_PREFIX = 'Users';
const ADMIN_METRIC_PREFIX = 'Metrics';

const STUDENT_CREATE_PREDICTION_PREFIX = 'Predict';

export {
  LOGIN_PREFIX,
  REGISTER_PREFIX,
  ADMIN_CREATE_PREFIX,
  ADMIN_DELETE_PREFIX,
  ADMIN_USERS_PREFIX,
  ADMIN_METRIC_PREFIX,
  STUDENT_CREATE_PREDICTION_PREFIX,
};
